export const GALLERY_FETCH_REQUEST = 'GALLERY_FETCH_REQUEST'
export const GALLERY_FETCH_SUCCESS = 'GALLERY_FETCH_SUCCESS'
export const GALLERY_FETCH_FAILURE = 'GALLERY_FETCH_FAILURE'

export const MEDIA_UPLOAD_REQUEST = 'MEDIA_UPLOAD_REQUEST'
export const MEDIA_UPLOAD_SUCCESS = 'MEDIA_UPLOAD_SUCCESS'
export const MEDIA_UPLOAD_FAILURE = 'MEDIA_UPLOAD_FAILURE'

export const MEDIA_DELETE_REQUEST = 'MEDIA_DELETE_REQUEST'
export const MEDIA_DELETE_SUCCESS = 'MEDIA_DELETE_SUCCESS'
export const MEDIA_DELETE_FAILURE = 'MEDIA_DELETE_FAILURE'

